name: Packer Checks

on:
  pull_request:
    # branches: 
    #   - main
    paths:
      - '**.pkr.hcl'  # Adjust the pattern to match your Packer templates
    types:
      - opened
      - synchronize

jobs:
  packer_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Packer
      uses: hashicorp/setup-packer@v1

    - name: Format Packer Templates
      run: |
          packer fmt -check=true ami.pkr.hcl
          if [[ $? -ne 0 ]]; then
            echo "Packer formatting check failed. Please format your Packer templates before merging."

    - name: Validate Packer Templates
      run: packer validate ami.pkr.hcl
