name: Packer Checks

on:
  pull_request:
    # branches: 
    #   - main
    paths:
      - '**.pkr.hcl'  # Adjust the pattern to match your Packer templates
    types:
      - opened
      - synchronize

jobs:
  packer_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
        unzip packer_1.7.5_linux_amd64.zip
        chmod +x packer
        mv packer /usr/local/bin/
        packer init .
      shell: bash

    - name: Format Packer Templates
      run: packer fmt -check=true ami.pkr.hcl

    - name: Validate Packer Templates
      run: packer validate ami.pkr.hcl
